# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: miniapp_development
  username: postgres
  password: password
  host: db
  port: 5432

test:
  <<: *default
  database: miniapp_test
  username: postgres
  password: password
  host: db
  port: 5432

production:
  <<: *default
  database: miniapp_production
  username: postgres
  password: password
  host: db
  port: 5432
